import { ServiceType, ServiceConfig } from '../types/service.types';

/**
 * Service configurations
 */
export const SERVICES_CONFIG: Record<ServiceType, ServiceConfig> = {
  [ServiceType.FIREWALL]: {
    type: ServiceType.FIREWALL,
    name: 'Firewall',
    description: 'Blocks malicious traffic and filters requests',
    cost: 100,
    range: 5,
    damage: 10,
    attackSpeed: 1.0,
    health: 100,
    maxHealth: 100,
    upkeep: 5,
    color: '#FF5733',
    levels: [
      {
        level: 1,
        cost: 100,
        range: 5,
        damage: 10,
        attackSpeed: 1.0,
        health: 100,
        maxHealth: 100,
        upkeep: 5,
      },
      {
        level: 2,
        cost: 75,
        range: 6,
        damage: 15,
        attackSpeed: 1.2,
        health: 150,
        maxHealth: 150,
        upkeep: 7,
      },
      {
        level: 3,
        cost: 100,
        range: 7,
        damage: 20,
        attackSpeed: 1.5,
        health: 200,
        maxHealth: 200,
        upkeep: 10,
      },
    ],
  },
  [ServiceType.CDN]: {
    type: ServiceType.CDN,
    name: 'Content Delivery Network',
    description: 'Caches static content and reduces load',
    cost: 150,
    range: 8,
    damage: 5,
    attackSpeed: 2.0,
    health: 80,
    maxHealth: 80,
    upkeep: 8,
    color: '#33FF57',
    levels: [
      {
        level: 1,
        cost: 150,
        range: 8,
        damage: 5,
        attackSpeed: 2.0,
        health: 80,
        maxHealth: 80,
        upkeep: 8,
      },
      {
        level: 2,
        cost: 100,
        range: 10,
        damage: 8,
        attackSpeed: 2.5,
        health: 120,
        maxHealth: 120,
        upkeep: 12,
      },
      {
        level: 3,
        cost: 150,
        range: 12,
        damage: 12,
        attackSpeed: 3.0,
        health: 160,
        maxHealth: 160,
        upkeep: 16,
      },
    ],
  },
  [ServiceType.LOAD_BALANCER]: {
    type: ServiceType.LOAD_BALANCER,
    name: 'Load Balancer',
    description: 'Distributes traffic across services',
    cost: 200,
    range: 10,
    damage: 8,
    attackSpeed: 1.5,
    health: 120,
    maxHealth: 120,
    upkeep: 10,
    color: '#3357FF',
    levels: [
      {
        level: 1,
        cost: 200,
        range: 10,
        damage: 8,
        attackSpeed: 1.5,
        health: 120,
        maxHealth: 120,
        upkeep: 10,
      },
      {
        level: 2,
        cost: 150,
        range: 12,
        damage: 12,
        attackSpeed: 1.8,
        health: 180,
        maxHealth: 180,
        upkeep: 15,
      },
      {
        level: 3,
        cost: 200,
        range: 15,
        damage: 18,
        attackSpeed: 2.2,
        health: 240,
        maxHealth: 240,
        upkeep: 20,
      },
    ],
  },
  [ServiceType.CACHE]: {
    type: ServiceType.CACHE,
    name: 'Cache Server',
    description: 'Stores frequently accessed data',
    cost: 120,
    range: 6,
    damage: 6,
    attackSpeed: 2.5,
    health: 90,
    maxHealth: 90,
    upkeep: 6,
    color: '#FF33F6',
    levels: [
      {
        level: 1,
        cost: 120,
        range: 6,
        damage: 6,
        attackSpeed: 2.5,
        health: 90,
        maxHealth: 90,
        upkeep: 6,
      },
      {
        level: 2,
        cost: 80,
        range: 8,
        damage: 10,
        attackSpeed: 3.0,
        health: 135,
        maxHealth: 135,
        upkeep: 9,
      },
      {
        level: 3,
        cost: 120,
        range: 10,
        damage: 15,
        attackSpeed: 3.5,
        health: 180,
        maxHealth: 180,
        upkeep: 12,
      },
    ],
  },
  [ServiceType.DATABASE]: {
    type: ServiceType.DATABASE,
    name: 'Database',
    description: 'Stores and retrieves persistent data',
    cost: 250,
    range: 7,
    damage: 15,
    attackSpeed: 0.8,
    health: 200,
    maxHealth: 200,
    upkeep: 15,
    color: '#F6FF33',
    levels: [
      {
        level: 1,
        cost: 250,
        range: 7,
        damage: 15,
        attackSpeed: 0.8,
        health: 200,
        maxHealth: 200,
        upkeep: 15,
      },
      {
        level: 2,
        cost: 200,
        range: 9,
        damage: 25,
        attackSpeed: 1.0,
        health: 300,
        maxHealth: 300,
        upkeep: 22,
      },
      {
        level: 3,
        cost: 250,
        range: 11,
        damage: 35,
        attackSpeed: 1.2,
        health: 400,
        maxHealth: 400,
        upkeep: 30,
      },
    ],
  },
  [ServiceType.AUTO_SCALER]: {
    type: ServiceType.AUTO_SCALER,
    name: 'Auto Scaler',
    description: 'Automatically scales services based on load',
    cost: 300,
    range: 12,
    damage: 12,
    attackSpeed: 1.8,
    health: 150,
    maxHealth: 150,
    upkeep: 20,
    color: '#33FFF6',
    levels: [
      {
        level: 1,
        cost: 300,
        range: 12,
        damage: 12,
        attackSpeed: 1.8,
        health: 150,
        maxHealth: 150,
        upkeep: 20,
      },
      {
        level: 2,
        cost: 250,
        range: 15,
        damage: 18,
        attackSpeed: 2.2,
        health: 225,
        maxHealth: 225,
        upkeep: 30,
      },
      {
        level: 3,
        cost: 300,
        range: 18,
        damage: 25,
        attackSpeed: 2.8,
        health: 300,
        maxHealth: 300,
        upkeep: 40,
      },
    ],
  },
};
